version: "3.8"

services:
  db:
    image: postgres:15
    expose:
      - 5432
    restart: unless-stopped
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
      POSTGRES_DB: danhenderson
    env_file:
      - backend/.env
    volumes:
      - ./backend/public/db:/var/lib/postgresql/data
  
  backend:
    build: ./backend
    command: uvicorn app.main:app --reload --workers 1 --host 0.0.0.0 --port 8000
    volumes:
      - ./backend:/usr/src/app
    ports:
      - 8004:8000
    depends_on:
      - db

  frontend:
    build: ./frontend
    command: npm start
    volumes:
      - ./frontend:/usr/src/app 
    ports:
      - 3000:3000 
    depends_on:
      - backend 