version: "3.8"

services:
  db:
    image: postgres:15
    ports:
      - "5431:5432"
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${DEFAULT_DATABASE_USER}
      POSTGRES_PASSWORD: ${DEFAULT_DATABASE_PASSWORD}
      POSTGRES_DB: ${DEFAULT_DATABASE_DB}
    env_file:
      - .env
    volumes:
      - ./backend/public/db:/var/lib/postgresql/data
      