version: "3.8"

services:
  db:
    image: postgres:15
    restart: unless-stopped
    ports:
      - "${DEFAULT_DATABASE_PORT}:5432"
    environment:
      - POSTGRES_DB=${DEFAULT_DATABASE_DB}
      - POSTGRES_USER=${DEFAULT_DATABASE_USER}
      - POSTGRES_PASSWORD=${DEFAULT_DATABASE_PASSWORD}
    env_file:
      - .env
    volumes:
      - ./public/db:/var/lib/postgresql/data